import {createRequire} from 'node:module';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
let playwright;try{playwright=require('playwright');}catch{playwright=require('/Users/ashutoshchatterjee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');}
const browser=await playwright.chromium.launch({headless:true,channel:process.env.AIRFRAME_BROWSER_CHANNEL||'chrome'});
const page=await browser.newPage({viewport:{width:1280,height:720},acceptDownloads:true});
const base=process.env.AIRFRAME_TEST_URL||'http://127.0.0.1:4173';
const results=[],errors=[];page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));
const createPage=browser.newPage.bind(browser);browser.newPage=async options=>{const p=await createPage(options);p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push(e.message));return p;};
await mkdir('test-results/remediation',{recursive:true});
async function test(name,fn){try{await fn();results.push({name,status:'passed'});console.log('PASS',name);}catch(e){results.push({name,status:'failed',error:e.message});console.error('FAIL',name,e.message);if(!page.isClosed())await page.screenshot({path:`test-results/remediation/failure-${results.length}.png`,fullPage:true});}}
async function route(hash){await page.goto(`${base}/#${hash}`);await page.waitForSelector('.factory-view,.investigation-view,.action-view');await page.waitForSelector('[data-queue],[data-scope],.diag-priority',{timeout:20000});}
async function close(){if(await page.locator('#frame-dialog').evaluate(e=>e.open))await page.keyboard.press('Escape');}
await test('Factory loads reported failure semantics and capture pattern queue',async()=>{await route('factory');assert.match(await page.locator('.incident-list').innerText(),/802\.1X/);await page.locator('[data-queue="patterns"]').click();assert.ok(await page.locator('[data-pattern]').count()>=2);const text=await page.locator('.incident-list').innerText();assert.match(text,/63 unique clients/);assert.match(text,/506 observations/);assert.match(text,/18 unique clients/);assert.match(await page.locator('.selected-summary').innerText(),/not proof of a shared cause/i);});
await test('Pattern selection opens existing investigation and member history',async()=>{await page.locator('[data-pattern]').first().click();await page.locator('[data-open-pattern]').click();await page.waitForSelector('.diag-member-list');assert.equal(await page.locator('[data-scope="pattern"]').getAttribute('aria-pressed'),'true');const member=page.locator('[data-client]').first();const alias=await member.getAttribute('data-client');await member.click();await page.waitForSelector('[data-history-filter]');assert.match(await page.locator('.diag-panel-head').innerText(),new RegExp(alias));assert.equal(await page.locator('[data-scope="history"]').getAttribute('aria-pressed'),'true');await page.locator('[data-back-pattern]').click();await page.waitForSelector('.diag-member-list');});
await test('Reason two pattern does not assert reason twenty three diagnosis',async()=>{const select=page.locator('[data-pattern-choice]');const options=await select.locator('option').evaluateAll(ns=>ns.map(n=>({value:n.value,text:n.textContent})));const option=options.find(x=>/termination|session|reason.?2/i.test(x.text));assert.ok(option,'Recurrence pattern option missing');await select.selectOption(option.value);assert.match(await page.locator('.diag-scoped').innerText(),/18 unique clients/);assert.doesNotMatch(await page.locator('.diag-failure').innerText(),/Reason 23/);});
await test('Client history includes security and termination filters with exact provenance',async()=>{await page.locator('[data-client]').first().click();await page.waitForSelector('[data-history-filter]');await page.locator('[data-history-filter]').selectOption('termination');await page.waitForFunction(()=>document.querySelector('.diag-table'));assert.match(await page.locator('.diag-table').innerText(),/termination|Deauthentication|Disassociation/i);await page.locator('[data-history-filter]').selectOption('eap');await page.waitForFunction(()=>document.querySelector('.diag-table'));if(await page.locator('.diag-table [data-diag-frame]').count()){const frame=page.locator('.diag-table [data-diag-frame]').first();const id=await frame.getAttribute('data-diag-frame');await frame.click();assert.match(await page.locator('#frame-dialog').innerText(),new RegExp(id));await close();}await page.locator('[data-history-filter]').selectOption('all');});
await test('History pagination changes membership and preserves client selection',async()=>{const before=await page.locator('.diag-table').innerText();const next=page.locator('[data-history-page="1"]');assert.ok(await next.isEnabled());await next.click();await page.waitForFunction(text=>document.querySelector('.diag-table')?.innerText!==text,before);const after=await page.locator('.diag-table').innerText();assert.notEqual(after,before);await page.locator('[data-history-page="-1"]').click();await page.waitForFunction(text=>document.querySelector('.diag-table')?.innerText===text,before);});
await test('Capture validity drawer distinguishes measurement and parser semantics',async()=>{await page.locator('[data-quality]').click();const text=await page.locator('#frame-dialog').innerText();assert.match(text,/Parsing success is not measurement validity/i);assert.match(text,/timing|timestamp/i);assert.match(text,/PHY|rate/i);assert.match(text,/snapshot|snaplen|length/i);await close();});
await test('Inventory drawer states observed versus expected and no localization',async()=>{await page.locator('[data-inventory]').click();const text=await page.locator('#frame-dialog').innerText();assert.match(text,/not an authoritative expected inventory/i);assert.match(text,/not declared offline/i);assert.match(text,/triangulation/i);assert.match(text,/Sensor RSSI|sensor.*signal/i);await close();});
await test('Episode separates connection security service and has no free metric strip',async()=>{await page.locator('[data-scope="episode"]').click();assert.equal(await page.locator('.ws-metrics').count(),0);assert.match(await page.locator('.diag-security').innerText(),/Open.system authentication/);assert.match(await page.locator('.diag-security').innerText(),/EAP|Enterprise security/);assert.match(await page.locator('.diag-security').innerText(),/service/i);assert.match(await page.locator('#app').innerText(),/physical recovery timing unvalidated/i);});
await test('Retry inspection is transmitter aware and avoids loss or serving AP rate claims',async()=>{await page.locator('[data-scope="history"]').click();await page.waitForSelector('[data-retries]');await page.locator('[data-retries]').click();const text=await page.locator('#frame-dialog').innerText();assert.match(text,/transmitter/i);assert.match(text,/Not a serving.AP retry rate/i);assert.match(text,/do not prove packet loss/i);await close();});
await test('Action presents scoped unsent request and independent outcome boundaries',async()=>{await page.locator('[data-action]').click();await page.waitForSelector('.diag-request');assert.match(await page.locator('.diag-priority').innerText(),/Exact cause unresolved/i);assert.match(await page.locator('.diag-request').innerText(),/Draft request — not sent/);assert.match(await page.locator('.diag-request').innerText(),/AAA|RADIUS/);assert.match(await page.locator('.diag-outcomes').innerText(),/Association/);assert.match(await page.locator('.diag-outcomes').innerText(),/Security/);assert.match(await page.locator('.diag-outcomes').innerText(),/Service/);assert.ok(await page.locator('.ws-action-event').count()<=8,'Raw event flood remains in anchor rail');});
await test('Action export retains privacy and inconclusive service boundary',async()=>{const exportButton=page.locator('[data-scoped-export]:visible,[data-export]:visible');const [file]=await Promise.all([page.waitForEvent('download'),exportButton.click()]);const text=await readFile(await file.path(),'utf8');assert.match(text,/unverified|unavailable|inconclusive/i);assert.doesNotMatch(text,/\b(?:[0-9a-f]{2}:){5}[0-9a-f]{2}\b/i);assert.doesNotMatch(text,/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/i);});
await test('Responsive layouts retain controls without page overflow',async()=>{for(const [width,height] of [[1280,720],[1024,768],[768,1024],[390,844]]){await page.setViewportSize({width,height});for(const hash of ['factory','investigate/AF-104','action/AF-104']){await route(hash);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${hash} overflows at ${width}`);await page.screenshot({path:`test-results/remediation/${hash.replace('/','-')}-${width}.png`,fullPage:true});}}});
await test('New controls have accessible names and drawer focus returns',async()=>{await page.setViewportSize({width:1280,height:720});await route('investigate/AF-104');await page.locator('[data-quality]').focus();await page.keyboard.press('Enter');await page.keyboard.press('Tab');assert.ok(await page.evaluate(()=>!!document.activeElement.closest('#frame-dialog')));await page.keyboard.press('Escape');assert.equal(await page.locator('[data-quality]').evaluate(e=>e===document.activeElement),true);const unnamed=await page.locator('button,input,select,textarea').evaluateAll(ns=>ns.filter(n=>n.getBoundingClientRect().width&&n.getBoundingClientRect().height).filter(n=>!((n.getAttribute('aria-label')||n.textContent||'').trim()||n.labels?.length)).map(n=>n.outerHTML));assert.deepEqual(unnamed,[]);});
await test('Noncurated member action and export remain bound to selected client',async()=>{
 await page.locator('[data-scope="pattern"]').click();await page.waitForSelector('[data-client]');
 const members=await page.locator('[data-client]').evaluateAll(ns=>ns.map(n=>n.dataset.client));const client=members.find(x=>x!=='C-004');assert.ok(client);await page.locator(`[data-client="${client}"]`).click();await page.waitForSelector('[data-history-filter]');
 assert.match(await page.locator('.ws-page-heading').innerText(),new RegExp(client));await page.locator('[data-action]').click();await page.waitForSelector('[data-scoped-plan]');
 assert.match(await page.locator('.diag-priority').innerText(),new RegExp(client));assert.doesNotMatch(await page.locator('.diag-request').innerText(),/C-004/);
 await page.locator('.diag-extension [data-diag-frame]').first().click();assert.match(await page.locator('#frame-dialog').innerText(),/Deauthentication|Disassociation|EAP|Authentication|Association/);await close();
 const [file]=await Promise.all([page.waitForEvent('download'),page.locator('[data-scoped-export]').click()]);const text=await readFile(await file.path(),'utf8');assert.match(text,new RegExp(client));assert.doesNotMatch(text,/AF-104|C-004|S03-5099/);
 await page.locator('[name="criterion"]').fill('Test service criterion');await page.locator('[name="safeguard"]').fill('Test no-change approval safeguard');await page.getByRole('button',{name:'Save plan locally',exact:true}).click();assert.match(await page.locator('[data-plan-state]').innerText(),/Saved locally/);await page.reload();await page.waitForSelector('[data-scoped-plan]');assert.equal(await page.locator('[name="criterion"]').inputValue(),'Test service criterion');
});
await test('Diagnostic data failure is unavailable and retry restores same scope',async()=>{
 const p=await browser.newPage();await p.route('**/data-v3/index.json',r=>r.fulfill({status:503,body:'Unavailable'}));await p.goto(base+'/#investigate/AF-104');await p.waitForSelector('[data-retry-diagnostics]');assert.match(await p.locator('.diag-load-error').innerText(),/unavailable/i);await p.unroute('**/data-v3/index.json');await p.locator('[data-retry-diagnostics]').click();await p.waitForSelector('[data-scope]');assert.equal(await p.locator('[data-scope="episode"]').getAttribute('aria-pressed'),'true');await p.close();
});
await test('Chunk failure preserves selection, does not claim zero, and retry succeeds',async()=>{
 const p=await browser.newPage();await p.route('**/data-v3/clients/*.json',r=>r.fulfill({status:503,body:'Unavailable'}));await p.goto(base+'/#investigate/AF-104');await p.waitForSelector('[data-scope="history"]');await p.locator('[data-scope="history"]').click();await p.waitForSelector('[data-scope-retry]');assert.match(await p.locator('.diag-scoped').innerText(),/No conclusion/);assert.doesNotMatch(await p.locator('.diag-scoped').innerText(),/0 matching|healthy/);await p.unroute('**/data-v3/clients/*.json');await p.locator('[data-scope-retry]').click();await p.waitForSelector('[data-history-filter]');await p.close();
});
await test('Late history response cannot overwrite newer pattern selection',async()=>{
 const p=await browser.newPage();let release;await p.route('**/data-v3/clients/*.json',async r=>{await new Promise(resolve=>release=resolve);await r.continue();});await p.goto(base+'/#investigate/AF-104');await p.waitForSelector('[data-scope="history"]');await p.locator('[data-scope="history"]').click();await p.waitForSelector('.diag-scoped .diag-loading');await p.locator('[data-scope="pattern"]').click();await p.waitForSelector('.diag-member-list');assert.ok(release);release();await p.waitForTimeout(150);assert.equal(await p.locator('[data-scope="pattern"]').getAttribute('aria-pressed'),'true');assert.equal(await p.locator('.diag-member-list').count(),1);assert.equal(await p.locator('[data-history-filter]').count(),0);await p.close();
});
await test('Review screenshots explicitly identify each scope and viewport',async()=>{
 const p=await browser.newPage({viewport:{width:1280,height:720}});await p.goto(base+'/#factory');await p.waitForSelector('[data-queue]');await p.screenshot({path:'test-results/remediation/factory1280.png',fullPage:true});await p.locator('[data-open="AF-104"]').last().click();await p.waitForSelector('[data-scope]');await p.screenshot({path:'test-results/remediation/investigation1280.png',fullPage:true});await p.locator('[data-scope="history"]').click();await p.waitForSelector('[data-history-filter]');await p.screenshot({path:'test-results/remediation/history1280.png',fullPage:true});await p.locator('[data-scope="pattern"]').click();await p.waitForSelector('.diag-member-list');await p.screenshot({path:'test-results/remediation/pattern1280.png',fullPage:true});await p.locator('[data-action]').click();await p.waitForSelector('[data-scoped-plan]');await p.screenshot({path:'test-results/remediation/action1280.png',fullPage:true});await p.setViewportSize({width:390,height:844});await p.screenshot({path:'test-results/remediation/action-mobile.png',fullPage:true});await p.close();
});
await test('Replay pattern and history never retain historical counts or future stages',async()=>{
 const p=await browser.newPage();await p.goto(base+'/#investigate/AF-104');await p.waitForSelector('[data-scope]');await p.locator('[data-scope="pattern"]').click();await p.waitForSelector('.diag-member-list');assert.match(await p.locator('.diag-scoped').innerText(),/506 observations/);
 await p.locator('#mode-toggle').click();await p.locator('#global-range').evaluate(el=>{el.value=String(Number(el.min)+4_000_000);el.dispatchEvent(new Event('input',{bubbles:true}));});await p.waitForSelector('.diag-member-list');assert.doesNotMatch(await p.locator('.diag-scoped').innerText(),/506 observations|63 unique clients/);
 await p.locator('[data-scope="episode"]').click();await p.waitForSelector('.diag-security');assert.doesNotMatch(await p.locator('.diag-security').innerText(),/13\.127/);assert.equal(await p.locator('[data-diag-frame="S03-6135"]').count(),0);
 await p.locator('#mode-toggle').click();await p.waitForSelector('[data-scope]');await p.locator('[data-scope="pattern"]').click();await p.waitForSelector('.diag-member-list');assert.match(await p.locator('.diag-scoped').innerText(),/506 observations/);await p.close();
});
await test('Quality membership pagination and frame Back preserve exact selection',async()=>{
 const p=await browser.newPage();await p.goto(base+'/#investigate/AF-104');await p.waitForSelector('[data-quality]');await p.locator('[data-quality]').click();await p.locator('[data-quality-members]').first().click();await p.waitForSelector('[data-quality-page]');const first=await p.locator('#frame-dialog [data-diag-frame]').first().innerText();await p.locator('[data-quality-page="1"]').click();await p.waitForFunction(text=>document.querySelector('#frame-dialog [data-diag-frame]')?.textContent!==text,first);await p.locator('#frame-dialog [data-diag-frame]').first().click();await p.waitForSelector('#frame-details-back');await p.locator('#frame-details-back').click();await p.waitForSelector('[data-quality-back]');await p.locator('[data-quality-back]').click();assert.match(await p.locator('#frame-dialog').innerText(),/Complete finding membership/);await p.keyboard.press('Escape');await p.close();
});
await test('Every empty stage explains its boundary and history member navigation is functional',async()=>{
 const p=await browser.newPage();await p.goto(base+'/#investigate/AF-104');await p.waitForSelector('[data-stage-info]');const stages=await p.locator('[data-stage-info]').evaluateAll(ns=>ns.map(n=>n.dataset.stageInfo));for(const id of stages){await p.locator(`[data-stage-info="${id}"]`).click();await p.waitForSelector('#frame-dialog[open]');assert.ok((await p.locator('#frame-dialog').innerText()).length>80);await p.keyboard.press('Escape');}
 await p.locator('[data-scope="history"]').click();await p.waitForSelector('[data-history-filter]');await p.locator('.diag-table [data-diag-frame]').first().click();await p.waitForSelector('#frame-next');const before=await p.locator('#frame-dialog').innerText();await p.locator('#frame-next').click();assert.notEqual(await p.locator('#frame-dialog').innerText(),before);await p.locator('#frame-previous').click();assert.equal(await p.locator('#frame-dialog').innerText(),before);await p.keyboard.press('Escape');await p.close();
});
await test('Episode evidence request copy has explicit no-send feedback',async()=>{
 const p=await browser.newPage();await p.goto(base+'/#action/AF-104?scope=episode');await p.waitForSelector('[data-copy-request]');await p.locator('[data-copy-request]').click();await p.waitForFunction(()=>/copied|Clipboard unavailable/.test(document.querySelector('#toast')?.textContent||''));assert.match(await p.locator('.diag-request').innerText(),/Draft request — not sent/);await p.close();
});
await test('Pattern pages and history source transmitter filters operate independently',async()=>{
 const p=await browser.newPage();await p.goto(base+'/#investigate/AF-104?scope=pattern&pattern=PAT-23');await p.waitForSelector('[data-member-page]');const first=await p.locator('[data-client]').first().innerText();await p.locator('[data-member-page="1"]').click();assert.notEqual(await p.locator('[data-client]').first().innerText(),first);await p.locator('[data-member-page="-1"]').click();assert.equal(await p.locator('[data-client]').first().innerText(),first);await p.locator('[data-client]').first().click();await p.waitForSelector('[data-history-source]');await p.locator('[data-history-source]').selectOption('S03');await p.waitForFunction(()=>!!document.querySelector('[data-history-source]'));assert.ok((await p.locator('.diag-table tbody tr').allTextContents()).every(t=>/S03|No matching/.test(t)));await p.locator('[data-history-transmitter]').selectOption('all');await p.locator('[data-history-source]').selectOption('all');await p.close();
});
await test('Structured comparison recovery and earlier context controls are grounded and fresh',async()=>{
 const p=await browser.newPage();await p.goto(base+'/#investigate/AF-104?scope=episode');await p.waitForSelector('[data-diagnostic-question]');await p.getByText('Compare explanations',{exact:true}).click();assert.match(await p.locator('.diag-reasoning').innerText(),/Radio impairment/);await p.getByRole('button',{name:'Compare cases',exact:true}).click();await p.waitForSelector('.ws-answer');const before=await p.locator('.ws-answer').innerText();assert.match(before,/controller|authentication|reason/i);await p.getByRole('button',{name:'Establish recovery',exact:true}).click();await p.waitForFunction(text=>document.querySelector('.ws-answer')?.innerText!==text,before);assert.match(await p.locator('.ws-answer').innerText(),/service|application/i);await p.getByRole('button',{name:'Earlier context',exact:true}).click();await p.waitForSelector('[data-history-filter]');assert.equal(await p.locator('[data-scope="history"]').getAttribute('aria-pressed'),'true');await p.close();
});
await test('Blocked scoped-plan storage retains draft and usable export',async()=>{
 const p=await browser.newPage({acceptDownloads:true});await p.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('Blocked','QuotaExceededError');};});await p.goto(base+'/#action/AF-104?scope=history&client=C-001');await p.waitForSelector('[data-scoped-plan]');await p.locator('[name="criterion"]').fill('Retained scoped criterion');await p.getByRole('button',{name:'Save plan locally',exact:true}).click();assert.match(await p.locator('[data-plan-state]').innerText(),/unavailable|not saved|unsaved|blocked/i);assert.equal(await p.locator('[name="criterion"]').inputValue(),'Retained scoped criterion');const [file]=await Promise.all([p.waitForEvent('download'),p.locator('[data-scoped-export]').click()]);assert.match(await readFile(await file.path(),'utf8'),/Retained scoped criterion/);await p.close();
});
await test('No new runtime exceptions',async()=>assert.deepEqual(errors,[]));
await writeFile('test-results/remediation/ui-report.json',JSON.stringify({results,errors},null,2));await browser.close();if(results.some(r=>r.status==='failed'))process.exitCode=1;
